version: '3.5'

services:
  postgres:
    image: "postgres:13.2"
    container_name: postgres-loan
    volumes:
      - pgdata:/var/lib/postgres-loan/data
      - ./config/init-db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"

volumes:
  pgdata:
    driver: local