CREATE TABLE calculator
(
    id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          timestamp with time zone,
    loan_amount         bigint,
    interest_rate       integer,
    loan_term           integer,
    monthly_payment     bigint,
    total_interest      bigint,
    time_scope          varchar(50) NOT NULL
);
